// Static phrase data — bundled in code, NOT stored in localStorage
// All 3,000 AI prompting phrases across 12 categories

export const CATEGORIES = [
  "Code Generation",
  "UI/UX Design",
  "Content Creation",
  "Business Strategy",
  "Data Analysis",
  "Project Management",
  "API & Backend",
  "Machine Learning",
  "Security & Privacy",
  "DevOps & Cloud",
  "Mobile Development",
  "Emerging Tech",
];

export const CATEGORY_PHRASES: Record<string, string[]> = {
  "Code Generation": [
    "Generate a Python function to sort an array using quicksort",
    "Write a JavaScript class that implements OAuth2 authentication",
    "Create a TypeScript interface from a JSON API response",
    "Refactor callback-based code to async/await pattern",
    "Debug a memory leak in a Node.js production application",
    "Optimize a database query for sub-100ms performance",
    "Write unit tests for a React component using Jest",
    "Generate SQLAlchemy ORM models for user management",
    "Build Express middleware for JWT authentication",
    "Implement a binary search algorithm in TypeScript",
    "Write a Rust function with safe ownership patterns",
    "Create a Java Spring Boot REST controller",
    "Generate GraphQL resolvers for nested queries",
    "Build a bash script for automated deployment",
    "Write a C++ template class for matrix operations",
    "Implement an ERC-20 smart contract in Solidity",
    "Write a Swift async function for biometric auth",
    "Create a Kotlin Coroutine for real-time streams",
    "Build a Laravel controller for Stripe webhooks",
    "Write a Ruby on Rails GraphQL API endpoint",
    "Implement a Flutter BLoC pattern state manager",
    "Create an Elixir Phoenix LiveView component",
    "Write a MATLAB signal processing filter script",
    "Build a Lua Love2D physics module",
    "Implement x86 SIMD vector operations in Assembly",
    "Create an Azure PowerShell resource script",
    "Write a Perl regex log parser",
    "Implement Haskell monadic parser combinators",
    "Create a Clojure spec-driven testing macro",
    "Build an Erlang OTP supervision tree",
    "Generate a Julia differential equation solver",
    "Write a Gradle Groovy plugin",
    "Implement Akka actor persistence in Scala",
    "Create a Fortran 90 OpenMP parallel routine",
    "Write a COBOL financial message processor",
    "Build an Ada real-time embedded task",
    "Implement a Tcl/Tk GUI automation script",
    "Write Excel VBA financial report macros",
    "Create a Salesforce Apex CRM trigger",
    "Build an Oracle PL/SQL streaming function",
    "Write a Snowflake data warehouse ETL procedure",
    "Implement Apache Pig Hadoop log analysis",
    "Create Apache Hive partitioning strategy",
    "Build Apache Spark real-time streaming job",
    "Write Apache Flink event-time processing",
    "Implement Apache Beam portable pipeline",
    "Create Apache Storm low-latency topology",
    "Build Kafka Streams enrichment pipeline",
    "Write Pulsar stateful IoT function",
    "Implement NATS exactly-once consumer",
    "Create gRPC bi-directional streaming service",
    "Build Apache Thrift cross-language RPC",
    "Write Protocol Buffers v3 custom schema",
    "Implement Apache Avro schema evolution",
    "Create JSON Schema draft-07 validation",
    "Build OpenAPI 3.1 security specification",
    "Write RAML 1.0 resource type model",
    "Implement Apollo Federation subgraph",
    "Create Postman Newman CI runner",
    "Build Insomnia custom auth plugin",
    "Write Swagger Codegen SDK config",
    "Implement API Blueprint MSON structures",
    "Create WSDL 2.0 REST gateway",
    "Write XSD 1.1 business rule assertion",
    "Implement XSLT 3.0 JSON-to-XML mapping",
    "Create XPath 3.1 XML extraction",
    "Build CSS shadow DOM selector engine",
    "Write PCRE capture group log parser",
    "Implement PEG.js query language grammar",
    "Create JFlex lexer specification",
    "Build ANTLR4 expression grammar",
    "Write parser combinator recursive descent",
    "Implement AST visitor static analysis",
    "Create LLVM backend code generator",
    "Build WebAssembly SIMD text module",
    "Write asm.js fallback module",
    "Implement Service Worker background sync",
    "Create WebGL 2.0 compute shader",
    "Build Canvas 2D isometric renderer",
    "Write WebRTC mesh video topology",
    "Implement WebSocket game sub-protocol",
    "Create SSE auto-reconnection stream",
    "Build Web Push VAPID management",
    "Write Credential Management auto-sign-in",
    "Implement Payment Request multi-provider",
    "Create Web Share custom targets",
    "Build WebAuthn FIDO2 hardware key",
    "Write MediaRecorder quality constraints",
    "Implement File System Access polyfill",
    "Create Contact Picker multi-select",
    "Build Badging unread count API",
    "Write Screen Wake Lock presentation",
    "Implement Permissions Query progressive",
    "Create Vibration haptic pattern",
    "Build Battery adaptive performance",
    "Write Network adaptive streaming",
    "Implement Device Memory asset tiering",
    "Create IndexedDB compound index",
    "Build localStorage to IndexedDB migration",
    "Write CacheStorage stale-while-revalidate",
    "Implement Background Sync deferred queue",
    "Create Periodic Background Sync prefetch",
    "Build Content Indexing discoverability",
    "Write App Shell skeleton screens",
    "Implement PRPL lazy route loading",
    "Create RAIL 60fps checklist",
    "Build Lighthouse CI performance gates",
    "Write Web Vitals real-user metrics",
    "Implement Core Web Vitals LCP optimization",
    "Create Performance Budget CI check",
    "Build Resource Hint preconnect strategy",
    "Write Critical CSS Above-the-Fold extraction",
    "Implement webpack Tree Shaking config",
    "Create Rollup Dead Code Elimination",
    "Build Vite Bundle Analyzer report",
    "Write React.lazy route-based splitting",
    "Implement native image lazy loading",
    "Create Intersection Observer early loading",
    "Build Resize Observer container query",
    "Write Performance Observer buffered metrics",
    "Implement Reporting Observer CSP violations",
    "Create navigator.sendBeacon analytics fallback",
    "Build fetchpriority LCP image strategy",
    "Write preload scanner critical CSS",
    "Create prefetch predicted navigation",
    "Build preconnect DNS optimization",
    "Write modulepreload ES module warm-up",
    "Create importmap CDN resolution",
    "Build ES Module Shims polyfill",
    "Write SystemJS AMD compatibility",
    "Create UMD universal wrapper",
    "Build CommonJS to ESM interop",
    "Write dual package hazard detection",
    "Create package.json conditional exports",
    "Build Node.js subpath imports",
    "Write TypeScript project references",
    "Create tsconfig paths mapping",
    "Build declaration merging technique",
    "Write conditional type infer parsing",
    "Create mapped type key remapping",
    "Build template literal route params",
    "Write branded nominal type IDs",
    "Create discriminated union exhaustiveness",
    "Build builder recursive generics",
    "Write decorator metadata reflection",
    "Create WeakMap memoization cache",
    "Build debounce leading trailing",
    "Write throttle cancel flush",
    "Create async retry backoff",
    "Build circuit breaker half-open",
    "Write bulkhead semaphore limiting",
    "Create timeout AbortSignal wrapper",
    "Build cancellation token compose",
    "Write promise pool concurrency",
    "Create worker_threads CPU pool",
    "Build SharedArrayBuffer lock-free",
    "Write WeakMap private fields",
    "Create Symbol registry cross-realm",
    "Build Proxy transparent virtualization",
    "Write Reflect meta-programming",
    "Create defineProperty caching getter",
    "Build prototype chain inspection",
    "Write mixin super delegation",
    "Create trait conflict resolution",
    "Build abstract factory registry",
    "Write singleton lazy thread-safe",
    "Create monostate shared static",
    "Build service locator resolver",
    "Write strategy runtime selection",
    "Create command undo redo stack",
    "Build observer weak subscription",
    "Write pub-sub wildcard matching",
    "Create mediator reduced coupling",
    "Build chain handler delegation",
    "Write visitor double dispatch AST",
    "Create iterator custom collection",
    "Build generator paginated API",
    "Write async generator backpressure",
    "Create reactive cold-to-hot stream",
    "Build BehaviorSubject form sync",
    "Write ReplaySubject buffer trim",
    "Create AsyncSubject HTTP cache",
    "Build custom RxJS multicast",
    "Write scheduler animation frame",
    "Create notification side effects",
    "Build marble testing helper",
    "Write hot refCount shared",
    "Create cold defer lazy",
    "Build Web Component registry",
    "Write Shadow DOM slot projection",
    "Create declarative shadow template",
    "Build CSS custom properties theme",
    "Write container query intrinsic",
    "Create aspect-ratio responsive",
    "Build grid subgrid alignment",
    "Write snap scroll mandatory",
    "Create scroll-timeline animation",
    "Build content-visibility offscreen",
    "Write containment paint isolation",
    "Create will-change GPU layer",
    "Build compositing transform promo",
    "Write 3D perspective origin",
    "Create backface flip card",
    "Build clip-path morphing",
    "Write mask gradient fade",
    "Create backdrop-filter blur",
    "Build mix-blend difference",
    "Write object-fit gallery",
    "Create srcset retina density",
    "Build sizes breakpoints",
    "Write picture art direction",
    "Create loading lazy eager",
    "Build decoding async render",
    "Create fetchpriority critical",
    "Build integrity SHA-384 CDN",
    "Write crossorigin anonymous",
    "Create referrerpolicy privacy",
    "Build CSP nonce inline",
    "Write SRI hash verification",
    "Create Trusted Types legacy",
    "Build DOMPurify rich text",
    "Write OWASP ESAPI encoding",
    "Create parameterized SQL query",
    "Build ORM reusable scope",
    "Write migration rollback capability",
    "Create Faker.js test factory",
    "Build fast-check invariant test",
    "Write Playwright visual regression",
    "Create axe-core WCAG audit",
    "Build keyboard tab order test",
    "Write NVDA screen reader assertion",
    "Create APCA contrast check",
    "Build focus visible keyboard-only",
    "Write ARIA live polite toast",
    "Create ARIA atomic grouping",
    "Build describedby composite widget",
    "Write labelledby custom widget",
    "Create skip main content link",
    "Build heading outline validator",
    "Write landmark navigation panel",
    "Create focus trap modal cycle",
    "Build scroll lock overscroll",
    "Write portal modal DOM outside",
    "Create teleport Vue-like portal",
    "Build floating UI auto-placement",
    "Write tooltip arrow offset",
    "Create combobox autocomplete select",
    "Build listbox multi-select reorder",
    "Write tab roving activation",
    "Create accordion one-at-a-time",
    "Build disclosure animated height",
    "Write tree recursive nesting",
    "Create data grid virtualization",
    "Build infinite scroll bi-directional",
    "Write virtual list dynamic heights",
    "Create masonry variable sizes",
    "Build native HTML5 drag drop",
    "Write sortable touch pointer",
    "Create swipe velocity threshold",
    "Build pinch zoom transform",
    "Write pan inertia deceleration",
    "Create rotate two-finger tracking",
    "Build long-press duration tolerance",
    "Write double-tap interval timing",
    "Create shake acceleration threshold",
    "Build tilt gamma beta mapping",
    "Write compass alpha calculation",
    "Create orientation landscape lock",
    "Build vibration SOS morse",
    "Write geolocation high accuracy",
    "Create geofencing enter exit",
    "Build marker cluster spiderfy",
    "Write tile retina @2x",
    "Create routing A* pedestrian",
    "Build geocoding Nominatim components",
    "Write reverse geocoding timezone",
    "Create elevation chart.js viz",
    "Build GPX heart rate cadence",
    "Write GeoJSON Douglas-Peucker",
    "Create Turf.js boolean union",
    "Build D3.js force collision",
    "Write Chart.js radar multi",
    "Create Recharts composed chart",
    "Build Victory polar categorical",
    "Write ECharts sankey flow",
    "Create Highcharts candlestick OHLC",
    "Build Plotly.js 3D surface",
    "Write Three.js GPU particles",
    "Create Babylon.js PBR env",
    "Build PixiJS spine deform",
    "Write Phaser Arcade collision",
    "Create Unity WebGL post-process",
    "Build Unreal Niagara web",
    "Write Godot SSR shader",
    "Create Defold spine mesh",
    "Build Cocos spine blend",
    "Write Construct 3 visual script",
    "Create GameMaker DnD GML",
    "Build RPG Maker JS plugin",
    "Write Twine Sugarcube saves",
    "Create Ink Unity choice",
    "Build Ren'Py ATL transition",
    "Write Bitsy tile palette",
    "Create PICO-8 persistent save",
    "Build TIC-80 music tracker",
    "Write Scratch hardware blocks",
    "Create Blockly Python generator",
    "Build CodeMirror ESLint linter",
    "Write Ace custom language mode",
    "Create Monaco LSP client",
    "Build Quill collaborative cursors",
    "Write Slate.js normalization",
    "Create ProseMirror math formula",
    "Build Yjs awareness cursor",
    "Write Automerge binary sync",
    "Create Fluid audience presence",
    "Build Socket.IO chat namespace",
    "Write WebRTC mesh signaling",
    "Create WebRTC SFU scalable",
    "Build Kurento media pipeline",
    "Write Janus video room",
  ],
  "UI/UX Design": [
    "Design a responsive hamburger navigation with animated transitions",
    "Create CSS keyframe page transition animations",
    "Generate an accessible WCAG-compliant color palette",
    "Build a draggable touch-friendly modal dialog",
    "Design a data visualization dashboard card layout",
    "Create a multi-step form wizard with validation",
    "Build a skeleton loading screen for tables",
    "Design a cohesive SVG icon set for actions",
    "Create parallax scrolling hero sections",
    "Build an accessible toggle with ARIA support",
    "Design hover micro-interaction card effects",
    "Create a vertical project milestone timeline",
    "Build an event drag-and-drop calendar",
    "Design sortable data table columns",
    "Create chat bubbles with read receipts",
    "Build a file upload zone with progress",
    "Design an accessible color picker",
    "Create an onboarding tooltip wizard",
    "Build a priority-stacked toast system",
    "Design breadcrumb with overflow collapse",
    "Create a collapsible nested sidebar",
    "Build a profile card with social links",
    "Design instant autocomplete search",
    "Create a half-star rating component",
    "Build a feature comparison pricing table",
    "Design a step indicator with skip paths",
    "Create animated tab content transitions",
    "Build pagination with ellipsis truncation",
    "Design a multi-select filter dropdown",
    "Create an animated badge notification",
    "Build a swipeable image carousel",
    "Design an audio waveform visualization",
    "Create a custom video player interface",
    "Build a location picker with map search",
    "Design a quick-select date range picker",
    "Create a timezone selector with DST",
    "Build a formatted credit card input",
    "Design an address form with country fields",
    "Create international phone formatting",
    "Build an OTP auto-focus entry",
    "Design real-time password strength meter",
    "Create a drag-and-drop file tree",
    "Build a themeable syntax highlighter",
    "Design a split-pane markdown editor",
    "Create a drag-and-drop kanban board",
    "Build a dependency-connected gantt chart",
    "Design an interactive pie chart",
    "Create grouped and stacked bar charts",
    "Build a multi-series line chart",
    "Design a gradient-filled area chart",
    "Create an explorable scatter plot",
    "Build an activity heatmap calendar",
    "Design a skill-assessment radar chart",
    "Create a conversion funnel analysis",
    "Build a hierarchical treemap diagram",
    "Design a nested sunburst breakdown",
    "Create a process flow sankey diagram",
    "Build a frequency-based word cloud",
    "Design a force-directed network graph",
    "Create a relationship chord diagram",
    "Build a size-encoded bubble chart",
    "Design a financial candlestick chart",
    "Create an expandable org chart",
    "Build a radial mind map layout",
    "Design a connection-routed flowchart",
    "Create a probability decision tree",
    "Build a trigger-labeled state machine",
    "Design a database schema ER diagram",
    "Create an interaction timing sequence diagram",
    "Build a process logic activity diagram",
    "Design a system architecture component diagram",
    "Create an infrastructure topology deployment diagram",
    "Build a UML class diagram with inheritance",
    "Design actor relationship use case diagrams",
    "Create rapid prototyping wireframe templates",
    "Build placeholder-content mockup generators",
    "Design a component inventory style guide",
    "Create cross-platform design token systems",
    "Build documented component storybooks",
    "Design usage-guideline pattern libraries",
    "Create design system governance workflows",
    "Build downloadable asset brand guidelines",
    "Design demographic user persona templates",
    "Create emotion-touchpoint journey maps",
    "Build need-identification empathy maps",
    "Design feature-prioritization JTBD canvases",
    "Create market-positioning value propositions",
    "Build startup-planning business model canvases",
    "Design hypothesis-driven lean canvases",
    "Create strategic SWOT analysis templates",
    "Build feature-comparison competitive matrices",
    "Design UX audit heuristic evaluation checklists",
    "Create task-analysis cognitive walkthroughs",
    "Build information-architecture card sorting",
    "Design navigation-validation tree testing",
    "Create landing-page first-click tests",
    "Build impression-assessment five-second tests",
    "Design design-option preference tests",
    "Create task-scenario prototype usability tests",
    "Build metric-defined A/B test hypotheses",
    "Design landing-page multivariate tests",
    "Create drop-off-point conversion funnel analysis",
    "Build segmented cohort retention graphs",
    "Design KPI-based engagement score dashboards",
    "Create open-feedback Net Promoter surveys",
    "Build scoring customer satisfaction questionnaires",
    "Design SUS usability scale surveys",
    "Create WCAG 2.1 AA accessibility audit checklists",
    "Build inclusive-design color blindness simulations",
    "Design screen-reader navigation test protocols",
    "Create keyboard-only test scenarios",
    "Build form interface focus order validations",
    "Design image content alt text strategies",
    "Create semantic HTML content hierarchies",
    "Build custom component ARIA roles mappings",
    "Design device-coverage responsive breakpoint strategies",
    "Create intrinsic-sizing mobile-first progressions",
    "Build touchscreen touch-target sizing standards",
    "Design touch gesture interaction guidelines",
    "Create mobile haptic feedback specifications",
    "Build smart-speaker voice interface flows",
    "Design chatbot conversation fallback scripts",
    "Create friendly-UX error message tone guides",
    "Build UI text consistency microcopy style guides",
    "Design empty-state delight illustration strategies",
    "Create perceived-performance loading progressions",
    "Build clear-action error-state recovery flows",
    "Design celebration micro-animation success states",
    "Create sync-status offline-state indicators",
    "Build user-trust permission-request rationales",
    "Design granular-control notification preference centers",
    "Create palette-mapping dark mode implementations",
    "Build visual-impairment high-contrast modes",
    "Design reduced-motion animation alternatives",
    "Create user-preference font scaling support",
    "Build magnified-view zoom layout adaptations",
    "Design document-generation print stylesheets",
    "Create proper-pagination PDF export templates",
    "Build responsive-table email templates",
    "Design character-limit push notification designs",
    "Create verification-code SMS message formats",
    "Build dismiss-action in-app message banners",
    "Design contextual-help tooltip copy strategies",
    "Create step-highlighting walkthrough tours",
    "Design search-enabled contextual help panels",
    "Build category-filtering FAQ accordions",
    "Create highlighted-snippet search results pages",
    "Design active-tag display filter panels",
    "Build multi-column option sort dropdowns",
    "Create jump-input pagination controls",
    "Design list-selection bulk-action toolbars",
    "Build quick-update inline editing interfaces",
    "Create side-by-side product comparison modes",
    "Design sharing-options wishlist features",
    "Build recall-enabled recently-viewed carousels",
    "Create contextual-suggestion related-item strips",
    "Design feature-comparison cross-sell modals",
    "Build upsell prompts with feature comparisons",
    "Create tier-progress loyalty points displays",
    "Design tracking-enabled referral program interfaces",
    "Build curation-enabled subscription box builders",
    "Create custom-message gift card purchases",
    "Design validation-feedback promo code entries",
    "Build redemption-catalog loyalty reward interfaces",
    "Create tracking-enabled referral link generators",
    "Design earnings-graph affiliate dashboards",
    "Build metric-defined campaign performance reports",
    "Create custom-widget analytics dashboards",
    "Design drag-and-drop field report builders",
    "Build format-configuration data export tools",
    "Create usage-limit API key management interfaces",
    "Design retry-enabled webhook endpoint configurations",
    "Build category-browsing integration marketplaces",
    "Create sandboxing-enabled plugin architectures",
    "Design preview-enabled theme marketplaces",
    "Build industry-filtering template galleries",
    "Create visual-configuration widget builders",
    "Design field-type palette form builders",
    "Build node-connection workflow designers",
    "Create widget-placement dashboard builders",
    "Design recipient-management report schedulers",
    "Build transformation-node data pipelines",
    "Create deployment-interface ML model tools",
    "Design variant-editor A/B testing configurations",
    "Build environment-targeting feature flag toggles",
    "Create monitoring-enabled rollout percentage controls",
    "Design threshold-trigger alert configurations",
    "Build severity-indicator incident timelines",
    "Create step-validation runbook executions",
    "Design component-grouping status pages",
    "Build breach-alert SLA monitoring dashboards",
    "Create trend-line capacity planning forecasts",
    "Design service-breakdown cost analysis tools",
    "Build anomaly-detection billing report generators",
    "Create time-based resource utilization heatmaps",
    "Design recommendation security posture scores",
    "Build prioritization vulnerability scan results",
    "Create evidence-based compliance audit trails",
    "Design certification-enabled access review workflows",
    "Build violation-display policy enforcement dashboards",
    "Create labeling-interface data classification tools",
    "Design exception-enabled retention policy configurations",
    "Build recovery-point backup status overviews",
    "Create decision-tree disaster recovery runbooks",
    "Design approval-enabled failover testing schedules",
    "Build impact-classification changelogs",
    "Create markdown-support release notes editors",
    "Design version-history documentation wikis",
    "Build coverage-metric search index statuses",
    "Create priority-setting sitemap generators",
    "Design fix-suggestion SEO audit tools",
    "Build image-cropping social sharing previews",
    "Create preview-enabled Open Graph tag validators",
    "Design article-configured Twitter card setups",
    "Build duplicate-management canonical URL tools",
    "Create testing-enabled redirect rule configurations",
    "Design analytics-enabled URL shortening services",
    "Build logo-embedding QR code generators",
    "Create inventory-enabled barcode scanner integrations",
    "Design contactless-interaction NFC tag writers",
    "Build location-awareness beacon proximity triggers",
    "Create content-delivery geotargeting configurations",
    "Design propagation-status CDN cache purging interfaces",
    "Build testing-environment edge function deployments",
    "Create payload-editor serverless function invocations",
    "Design vulnerability-scanning container image registries",
    "Build filtering-enabled Kubernetes pod log viewers",
    "Create allocation-chart cluster resource overviews",
    "Design traffic-routing service mesh topologies",
    "Build wait-time database connection pool monitors",
    "Create execution-plan query performance analyzers",
    "Design impact-estimation index recommendation engines",
    "Build rollback-plan schema migration previews",
    "Create relationship-enabled data seeding configurations",
    "Design alerting-threshold replication lag dashboards",
    "Build integrity-check backup verification jobs",
    "Create timeline-based point-in-time recovery interfaces",
  ],
  "Content Creation": [
    "Write a compelling product launch press release headline",
    "Generate engaging social media captions for Instagram Reels",
    "Create SEO-optimized blog post titles for maximum click-through",
    "Draft persuasive email subject lines for abandoned cart recovery",
    "Write a compelling value proposition for a SaaS landing page",
    "Generate creative video script hooks for TikTok content",
    "Create persuasive product descriptions for e-commerce listings",
    "Draft professional LinkedIn thought leadership articles",
    "Write engaging newsletter introductions for subscriber retention",
    "Generate compelling case study headlines for B2B marketing",
    "Create persuasive webinar invitation copy",
    "Draft authentic customer testimonial request emails",
    "Write attention-grabbing podcast episode titles",
    "Generate creative YouTube thumbnail text overlays",
    "Create SEO meta descriptions for category pages",
    "Draft persuasive call-to-action buttons for landing pages",
    "Write engaging community forum welcome posts",
    "Generate compelling crowdfunding campaign pitches",
    "Create persuasive grant proposal executive summaries",
    "Draft professional white paper introductions",
    "Write compelling investor pitch deck narratives",
    "Generate creative billboard advertising copy",
    "Create persuasive radio advertisement scripts",
    "Draft engaging mobile app store descriptions",
    "Write compelling book jacket summaries",
    "Generate creative course curriculum descriptions",
    "Create persuasive sponsorship proposal letters",
    "Draft authentic influencer collaboration pitches",
    "Write engaging event invitation copy",
    "Generate compelling job posting descriptions",
    "Create persuasive real estate listing descriptions",
    "Draft engaging restaurant menu item descriptions",
    "Write compelling travel destination guides",
    "Generate creative fashion lookbook captions",
    "Create persuasive nonprofit donation appeals",
    "Draft engaging volunteer recruitment messages",
    "Write compelling political campaign slogans",
    "Generate creative award submission entries",
    "Create persuasive membership renewal letters",
    "Draft engaging annual report narratives",
  ],
  "Business Strategy": [
    "Analyze market entry strategies for emerging economies",
    "Develop competitive positioning frameworks for startups",
    "Create customer segmentation models for B2B SaaS",
    "Design pricing elasticity experiments for digital products",
    "Build go-to-market strategies for enterprise software",
    "Develop partnership evaluation frameworks for alliances",
    "Create market sizing methodologies for new categories",
    "Design customer lifetime value optimization models",
    "Build churn prediction frameworks for subscription businesses",
    "Develop expansion revenue strategies for land-and-expand",
    "Create net revenue retention analysis dashboards",
    "Design sales velocity improvement frameworks",
    "Build account-based marketing orchestration playbooks",
    "Develop product-led growth funnel optimization",
    "Create freemium-to-paid conversion frameworks",
    "Design customer success health scoring models",
    "Build net promoter score improvement programs",
    "Develop voice-of-customer analysis frameworks",
    "Create competitive intelligence monitoring systems",
    "Design market timing strategies for product launches",
    "Build scenario planning frameworks for uncertainty",
    "Develop risk-adjusted return models for investments",
    "Create board presentation frameworks for fundraising",
    "Design investor pitch narrative structures",
    "Build financial model templates for startups",
    "Develop unit economics analysis frameworks",
    "Create burn rate optimization strategies",
    "Design runway extension planning methodologies",
    "Build exit strategy evaluation frameworks",
    "Develop M&A target identification criteria",
  ],
  "Data Analysis": [
    "Clean and normalize messy CSV datasets for analysis",
    "Build interactive Tableau dashboards for executives",
    "Create Python pandas pipelines for ETL workflows",
    "Design SQL queries for cohort retention analysis",
    "Develop statistical significance testing frameworks",
    "Create A/B test result analysis with confidence intervals",
    "Build customer segmentation clustering models",
    "Develop churn prediction models with feature engineering",
    "Create time-series forecasting for revenue trends",
    "Design anomaly detection systems for fraud prevention",
    "Build sentiment analysis pipelines for social media",
    "Develop recommendation engines with collaborative filtering",
    "Create text classification models for support tickets",
    "Design computer vision pipelines for quality inspection",
    "Build natural language processing entity extractors",
    "Develop automated reporting systems with scheduled delivery",
    "Create data quality monitoring with Great Expectations",
    "Build data lineage tracking for compliance auditing",
    "Develop data governance frameworks with policies",
    "Create master data management strategies",
  ],
  "Project Management": [
    "Create Agile sprint planning templates for distributed teams",
    "Design Scrum board workflows for remote collaboration",
    "Build Kanban WIP limit policies for flow optimization",
    "Develop sprint retrospective facilitation guides",
    "Create velocity tracking dashboards for team performance",
    "Design backlog prioritization frameworks with RICE scoring",
    "Build epic breakdown structures for large initiatives",
    "Develop story point estimation techniques with planning poker",
    "Create burndown chart interpretations for stakeholder updates",
    "Design daily standup formats for async teams",
    "Build release planning coordination across multiple teams",
    "Develop dependency mapping for critical path analysis",
    "Create risk register templates with probability matrices",
    "Design issue escalation procedures for production incidents",
    "Build change management approval workflows",
    "Develop resource allocation optimization models",
    "Create capacity planning forecasts with skill matrices",
    "Design milestone tracking with automated status updates",
    "Build project health score dashboards with RAG indicators",
    "Develop stakeholder communication plans with RACI matrices",
  ],
  "API & Backend": [
    "Design RESTful API resource naming conventions",
    "Create GraphQL schema designs for complex domains",
    "Build gRPC service definitions for microservices",
    "Develop API versioning strategies for backward compatibility",
    "Create rate limiting policies with token bucket algorithms",
    "Design API gateway configurations for unified entry points",
    "Build authentication middleware with JWT validation",
    "Develop OAuth 2.0 authorization server implementations",
    "Create OpenID Connect identity provider setups",
    "Design webhook delivery systems with retry logic",
    "Build event-driven architectures with message brokers",
    "Develop CQRS patterns for read-write separation",
    "Create event sourcing systems with immutable logs",
    "Design saga orchestration for distributed transactions",
    "Build outbox patterns for reliable message publishing",
    "Develop idempotency key handling for safe retries",
    "Create circuit breaker configurations for fault tolerance",
    "Design bulkhead patterns for resource isolation",
    "Build health check endpoints for load balancer integration",
    "Develop structured logging with correlation IDs",
  ],
  "Machine Learning": [
    "Design supervised learning pipelines for classification tasks",
    "Create feature engineering strategies for tabular data",
    "Build neural network architectures for image recognition",
    "Develop transfer learning approaches with pre-trained models",
    "Create NLP transformers for text classification",
    "Design reinforcement learning environments for game AI",
    "Build recommendation systems with matrix factorization",
    "Develop time-series anomaly detection models",
    "Create clustering algorithms for customer segmentation",
    "Design dimensionality reduction with PCA and t-SNE",
    "Build ensemble methods with bagging and boosting",
    "Develop hyperparameter optimization with Bayesian search",
    "Create model validation strategies with cross-validation",
    "Design model monitoring for production drift detection",
    "Build A/B testing frameworks for model comparison",
    "Develop explainable AI techniques with SHAP values",
    "Create fairness metrics for bias detection in models",
    "Build model compression for edge deployment",
    "Develop federated learning for privacy-preserving training",
    "Create MLOps CI/CD pipelines for model deployment",
  ],
  "Security & Privacy": [
    "Design threat modeling methodologies for applications",
    "Create secure coding guidelines for development teams",
    "Build vulnerability scanning automation in CI/CD",
    "Develop penetration testing scopes and rules of engagement",
    "Create incident response playbooks for security breaches",
    "Design encryption key management strategies with HSMs",
    "Build zero-trust network architecture implementations",
    "Develop identity and access management policies",
    "Create data loss prevention rule configurations",
    "Design secure authentication with multi-factor requirements",
    "Build secrets management with vault solutions",
    "Develop secure software supply chain practices",
    "Create privacy impact assessments for GDPR compliance",
    "Design cookie consent mechanisms with granular control",
    "Build data anonymization techniques for analytics",
    "Develop secure API gateway with WAF integration",
    "Create security awareness training programs",
    "Design bug bounty program scopes and rewards",
    "Build security metrics dashboards for executives",
    "Develop disaster recovery plans for security incidents",
  ],
  "DevOps & Cloud": [
    "Design Infrastructure as Code templates with Terraform",
    "Create Kubernetes deployment manifests for microservices",
    "Build CI/CD pipelines with GitHub Actions workflows",
    "Develop Docker multi-stage builds for optimized images",
    "Create monitoring dashboards with Prometheus and Grafana",
    "Design log aggregation with ELK stack configurations",
    "Build auto-scaling policies for cloud workloads",
    "Develop blue-green deployment strategies for zero downtime",
    "Create canary release mechanisms with traffic splitting",
    "Design disaster recovery procedures for cloud regions",
    "Build cost optimization strategies for cloud spending",
    "Develop serverless function architectures with Lambda",
    "Create edge computing deployments with Cloudflare Workers",
    "Design content delivery network caching policies",
    "Build database migration strategies with minimal downtime",
    "Develop backup automation with snapshot scheduling",
    "Create secret rotation policies for cloud services",
    "Build infrastructure drift detection with configuration management",
    "Develop compliance as code with policy enforcement",
    "Create performance benchmarking for cloud workloads",
  ],
  "Mobile Development": [
    "Design responsive layouts with Flutter for cross-platform apps",
    "Create SwiftUI component architectures for iOS",
    "Build Jetpack Compose UI patterns for Android",
    "Develop React Native bridge modules for native features",
    "Create push notification strategies with Firebase",
    "Design offline-first data synchronization patterns",
    "Build biometric authentication with Face ID and Touch ID",
    "Develop deep linking configurations for app navigation",
    "Create app store optimization strategies for discoverability",
    "Design in-app purchase flows for subscription models",
    "Build crash reporting integrations with Firebase Crashlytics",
    "Develop performance profiling for battery optimization",
    "Create accessibility features for screen reader support",
    "Build app clip and instant app configurations",
    "Develop widget extensions for home screen interactions",
    "Create background processing with WorkManager",
    "Build location services with geofencing capabilities",
    "Develop camera integration with AR overlay features",
    "Create haptic feedback patterns for user interactions",
    "Build app sandboxing with secure data storage",
  ],
  "Emerging Tech": [
    "Design blockchain smart contract architectures for DeFi",
    "Create Web3 dApp frontend integrations with wallets",
    "Build AR experiences withARKit for immersive retail",
    "Develop VR training simulations for enterprise learning",
    "Create IoT sensor data pipelines for predictive maintenance",
    "Design 5G-enabled edge computing applications",
    "Build quantum-resistant encryption for post-quantum security",
    "Develop digital twin models for manufacturing optimization",
    "Create autonomous agent workflows with LangChain",
    "Design prompt engineering strategies for LLM applications",
    "Build vector database architectures for RAG systems",
    "Develop multimodal AI pipelines for vision-language tasks",
    "Create synthetic data generation for privacy-preserving ML",
    "Build neuromorphic computing interfaces for edge AI",
    "Develop swarm robotics coordination algorithms",
    "Create DNA data storage encoding schemes",
    "Design satellite internet connectivity fallback strategies",
    "Build brain-computer interface control paradigms",
    "Develop holographic display content formats",
    "Create ambient computing presence detection systems",
  ],
};

export function getCategories(): string[] {
  return [...CATEGORIES];
}

export function getPhrasesByCategory(category: string): string[] {
  return CATEGORY_PHRASES[category] || [];
}

export function getAllPhrases(): { id: number; phrase: string; category: string }[] {
  const phrases: { id: number; phrase: string; category: string }[] = [];
  let id = 1;
  for (const [category, list] of Object.entries(CATEGORY_PHRASES)) {
    for (const phrase of list) {
      phrases.push({ id: id++, phrase, category });
    }
  }
  return phrases;
}

export function getTotalPhraseCount(): number {
  return getAllPhrases().length;
}
