export function seedPhrases() {
  const templates: Record<string, string[]> = {
    "Code Generation": [
      "Generate a Python function to sort an array",
      "Write a JavaScript class that implements user authentication",
      "Create a TypeScript script to automate data backup",
      "Refactor this code to use async/await pattern",
      "Debug this memory leak error in production",
      "Optimize this function for performance",
      "Write unit tests for this authentication module",
      "Generate interfaces for this API response",
      "Create a React component with real-time updates",
      "Build a middleware for role-based access control",
      "Implement a binary search algorithm in Go",
      "Write a Rust function for safe memory handling",
      "Create a Java Spring Boot REST controller",
      "Generate SQLAlchemy models for user management",
      "Build a GraphQL resolver for nested queries",
      "Write a shell script for automated deployment",
      "Create a C++ class for matrix operations",
      "Implement a blockchain smart contract in Solidity",
      "Write a Swift function for biometric authentication",
      "Generate a Kotlin coroutine for background processing",
      "Create a PHP Laravel controller for payment handling",
      "Build a Ruby on Rails API for content management",
      "Write a Dart function for Flutter state management",
      "Implement an Elixir GenServer for concurrent tasks",
      "Create a MATLAB script for signal processing",
    ],
    "UI/UX Design": [
      "Design a responsive navigation with mobile-first approach",
      "Create a CSS animation for page transitions",
      "Generate a color palette for dark theme",
      "Design a modal dialog with drag and drop",
      "Build a dashboard layout with metrics cards",
      "Create a form with multi-step validation",
      "Design a loading skeleton for data tables",
      "Generate SVG icons for action buttons",
      "Create a parallax scroll effect for hero section",
      "Design an accessible toggle component",
      "Build a card grid with hover animations",
      "Create a timeline component for project history",
      "Design a calendar interface for scheduling",
      "Generate a data table with sortable columns",
      "Create a chat bubble interface for messaging",
      "Design a file upload zone with drag and drop",
      "Build a color picker with accessibility features",
      "Create an onboarding wizard with progress steps",
      "Design a notification toast system",
      "Generate a breadcrumb navigation pattern",
      "Create a sidebar with collapsible sections",
      "Design a profile card with social links",
      "Build a search interface with auto-complete",
      "Create a rating component with star icons",
      "Design a pricing table with feature comparisons",
    ],
    "API & Backend": [
      "Design a REST API endpoint for user profiles",
      "Create a GraphQL schema for e-commerce data",
      "Implement JWT authentication with refresh tokens",
      "Build a WebSocket server for real-time chat",
      "Create API rate limiting with Redis",
      "Design a webhook handler for Stripe payments",
      "Implement OAuth 2.0 with Google login",
      "Create OpenAPI documentation for all endpoints",
      "Build a microservice for email notifications",
      "Design a caching strategy with CDN",
      "Implement request/response logging middleware",
      "Create a load balancer configuration",
      "Design a circuit breaker pattern",
      "Build an API gateway with request routing",
      "Implement content negotiation for APIs",
      "Create a service discovery mechanism",
      "Design event-driven architecture with message queue",
      "Build a CQRS pattern implementation",
      "Implement API versioning strategy",
      "Create health check endpoints",
      "Design a bulk import API for CSV data",
      "Build a search API with Elasticsearch",
      "Implement real-time analytics pipeline",
      "Create a data export API with filters",
      "Design API authentication with API keys",
    ],
    "Data Analysis": [
      "Parse CSV and calculate descriptive statistics",
      "Generate a correlation matrix for features",
      "Create a data visualization for sales trends",
      "Build a pandas query for cohort analysis",
      "Generate SQL for customer segmentation",
      "Create a machine learning pipeline for classification",
      "Implement data cleaning for missing values",
      "Build a sentiment analysis with NLP",
      "Generate a revenue forecast for next quarter",
      "Create a data pipeline with Apache Airflow",
      "Implement anomaly detection for metrics",
      "Build a recommendation engine with collaborative filtering",
      "Generate A/B test statistical report",
      "Create a geographic heat map visualization",
      "Implement time series decomposition",
      "Build a clustering algorithm for customer groups",
      "Generate automated data quality checks",
      "Create a real-time streaming analytics dashboard",
      "Implement survival analysis for churn prediction",
      "Build a network graph for social connections",
      "Generate text summarization for reports",
      "Create image classification with deep learning",
      "Implement principal component analysis",
      "Build a fraud detection model",
      "Generate automated insight extraction",
    ],
    "Content Creation": [
      "Write a blog post about AI in education",
      "Generate social media captions for product launch",
      "Create an email newsletter for weekly updates",
      "Write product descriptions for electronics",
      "Generate SEO meta tags for landing page",
      "Create a video script for tutorial content",
      "Write ad copy for Google Ads campaign",
      "Generate FAQ answers for SaaS product",
      "Create a content calendar for Q1 2026",
      "Write case studies for fintech clients",
      "Generate LinkedIn posts for thought leadership",
      "Create Instagram carousel post copy",
      "Write a press release for product announcement",
      "Generate TikTok video scripts",
      "Create podcast episode descriptions",
      "Write white paper executive summary",
      "Generate webinar invitation emails",
      "Create user onboarding email sequence",
      "Write comparison article for competitors",
      "Generate YouTube video descriptions",
      "Create Twitter thread about industry trends",
      "Write landing page hero copy",
      "Generate testimonial request emails",
      "Create product update changelog",
      "Write brand voice guidelines document",
    ],
    "Business Strategy": [
      "Draft a business plan for AI startup",
      "Create a go-to-market strategy for SaaS",
      "Generate competitive analysis for market entry",
      "Design a pricing model for subscription product",
      "Build a 5-year financial projection",
      "Create a pitch deck for investors",
      "Generate SWOT analysis for expansion",
      "Design a customer journey map",
      "Create OKRs for product team",
      "Build a revenue model with unit economics",
      "Implement a partnership strategy framework",
      "Design a brand positioning statement",
      "Create a market sizing analysis",
      "Build a customer acquisition strategy",
      "Generate a retention improvement plan",
      "Create an international expansion roadmap",
      "Design a product launch checklist",
      "Build a crisis management playbook",
      "Generate an innovation pipeline framework",
      "Create a stakeholder communication plan",
      "Design a change management strategy",
      "Build a sustainability business model",
      "Generate a talent acquisition strategy",
      "Create a digital transformation roadmap",
      "Design a competitive intelligence system",
    ],
    "Database & SQL": [
      "Write a SQL query for user order history",
      "Optimize this slow query with indexing",
      "Design a schema for social media platform",
      "Create an index for full-text search",
      "Write a migration for adding user roles",
      "Generate a database backup script",
      "Design sharding for high-volume data",
      "Create a stored procedure for reporting",
      "Implement full-text search with PostgreSQL",
      "Build a replication setup for read scaling",
      "Write a query for monthly sales aggregation",
      "Create a trigger for audit logging",
      "Design a schema for multi-tenant SaaS",
      "Generate a data retention policy script",
      "Create a materialized view for analytics",
      "Implement connection pooling configuration",
      "Write a query for recursive tree traversal",
      "Design a schema for versioned documents",
      "Create a partition strategy for time-series",
      "Generate database normalization analysis",
      "Build an ETL pipeline with SQL transformations",
      "Create a schema for recommendation engine",
      "Implement row-level security policies",
      "Design a schema for inventory management",
      "Generate a performance tuning checklist",
    ],
    "DevOps & Cloud": [
      "Create a Docker container for Node.js app",
      "Write a Kubernetes deployment manifest",
      "Set up CI/CD pipeline with GitHub Actions",
      "Configure Nginx reverse proxy with SSL",
      "Create Terraform modules for AWS infrastructure",
      "Design a monitoring dashboard with Grafana",
      "Implement blue-green deployment strategy",
      "Set up log aggregation with ELK stack",
      "Configure auto-scaling for web servers",
      "Create infrastructure as code templates",
      "Implement a secrets management with Vault",
      "Design a disaster recovery plan",
      "Create a Chaos Engineering experiment",
      "Set up service mesh with Istio",
      "Implement GitOps with ArgoCD",
      "Configure CDN for static assets",
      "Create a cost optimization strategy",
      "Design a multi-region deployment",
      "Implement zero-downtime deployments",
      "Set up vulnerability scanning in CI",
      "Create a container registry setup",
      "Implement progressive delivery with feature flags",
      "Design a serverless architecture",
      "Set up distributed tracing",
      "Create a cloud cost monitoring dashboard",
    ],
    "Mobile Development": [
      "Build a React Native login screen",
      "Create a Flutter widget for image gallery",
      "Implement push notifications with Firebase",
      "Design an offline-first data strategy",
      "Create a mobile navigation with bottom tabs",
      "Build a biometric authentication flow",
      "Optimize app startup performance",
      "Implement deep linking for content sharing",
      "Create a responsive image grid",
      "Build a mobile payment integration",
      "Implement gesture-based interactions",
      "Create a pull-to-refresh pattern",
      "Build an infinite scroll list component",
      "Implement background data sync",
      "Create a splash screen animation",
      "Build a native module for device sensors",
      "Implement app state persistence",
      "Create a barcode scanner feature",
      "Build a map integration with custom markers",
      "Implement biometric login fallback",
      "Create a dark mode toggle with persistence",
      "Build a video player with controls",
      "Implement in-app purchase flow",
      "Create a QR code generator",
      "Build a chat interface with real-time sync",
    ],
    "AI Model Tuning": [
      "Fine-tune BERT for sentiment classification",
      "Create few-shot prompt templates",
      "Design a RAG pipeline with vector store",
      "Implement chain-of-thought reasoning",
      "Build a prompt injection defense system",
      "Create embeddings for semantic search",
      "Design a model evaluation framework",
      "Implement RLHF for alignment",
      "Create a model comparison benchmark",
      "Build a hyperparameter tuning pipeline",
      "Implement knowledge distillation",
      "Create a model quantization strategy",
      "Design a multi-modal fusion architecture",
      "Build an active learning loop",
      "Implement model explainability with SHAP",
      "Create a synthetic data generation pipeline",
      "Design a model serving infrastructure",
      "Build a fine-tuning dataset creator",
      "Implement adversarial robustness testing",
      "Create a model monitoring dashboard",
      "Build a prompt optimization tool",
      "Implement federated learning setup",
      "Create a model compression workflow",
      "Design an ensemble model strategy",
      "Build an A/B testing framework for models",
    ],
    "Cybersecurity": [
      "Implement input sanitization for all fields",
      "Create a Content Security Policy header",
      "Design a threat model for web application",
      "Build an intrusion detection rule",
      "Implement zero-trust network architecture",
      "Create a vulnerability scanning schedule",
      "Design a secrets rotation strategy",
      "Build a SIEM alert configuration",
      "Implement end-to-end encryption",
      "Create an incident response playbook",
      "Implement multi-factor authentication",
      "Design a secure API authentication flow",
      "Build a penetration testing checklist",
      "Create a security awareness training plan",
      "Implement automated security testing",
      "Design a secure software development lifecycle",
      "Build a data loss prevention strategy",
      "Create an identity access management policy",
      "Implement secure code review process",
      "Build a ransomware protection strategy",
      "Create a compliance audit checklist",
      "Implement network segmentation plan",
      "Design a secure remote access solution",
      "Build a malware detection pipeline",
      "Create a security metrics dashboard",
    ],
    "Project Management": [
      "Create a sprint planning template",
      "Design a kanban board workflow",
      "Build a risk assessment matrix",
      "Generate user stories for checkout feature",
      "Create a retrospective meeting agenda",
      "Design a stakeholder communication plan",
      "Build a resource allocation chart",
      "Create a project milestone timeline",
      "Generate a bug triage process",
      "Design an agile ceremony schedule",
      "Implement a velocity tracking system",
      "Create a capacity planning framework",
      "Build a dependency mapping diagram",
      "Generate an escalation path document",
      "Create a quality assurance checklist",
      "Design a project handoff process",
      "Build a cross-team collaboration framework",
      "Generate a scope management process",
      "Create a change request workflow",
      "Implement a lessons learned repository",
      "Build a team performance dashboard",
      "Create an onboarding checklist for projects",
      "Design a conflict resolution framework",
      "Generate a project health scorecard",
      "Build a stakeholder feedback loop",
    ],
  };

  let id = 1;
  const phrases: any[] = [];

  for (const [category, list] of Object.entries(templates)) {
    for (const [index, english] of list.entries()) {
      phrases.push({
        id: id++,
        english,
        category,
        difficulty: (index % 5) + 1,
        tags: category,
        audio_generated: 0,
        audio_url: null,
        usage_example: null,
        created_at: new Date().toISOString(),
      });
    }
  }

  return phrases;
}
