import { getDb } from "../api/queries/connection";
import { phrases } from "./schema";
import { count } from "drizzle-orm";

const categories = [
  "Code Generation",
  "UI/UX Design",
  "API & Backend",
  "Data Analysis",
  "Content Creation",
  "Business Strategy",
  "Database & SQL",
  "DevOps & Cloud",
  "Mobile Development",
  "AI Model Tuning",
  "Cybersecurity",
  "Project Management",
];

const actions = [
  "Generate", "Create", "Build", "Design", "Implement", "Write", "Optimize", "Debug",
  "Refactor", "Develop", "Deploy", "Configure", "Automate", "Test", "Monitor",
  "Analyze", "Document", "Review", "Migrate", "Integrate", "Scale", "Secure",
  "Validate", "Measure", "Track", "Visualize", "Predict", "Classify", "Cluster",
  "Extract", "Transform", "Load", "Cache", "Index", "Query", "Route", "Filter",
  "Parse", "Serialize", "Encrypt", "Hash", "Sign", "Verify", "Authenticate",
  "Authorize", "Audit", "Backup", "Restore", "Archive", "Purge", "Replicate",
  "Shard", "Partition", "Normalize", "Denormalize", "Materialize", "Virtualize",
  "Containerize", "Orchestrate", "Schedule", "Trigger", "Stream", "Batch",
  "Paginate", "Sort", "Search", "Rank", "Recommend", "Personalize", "Customize",
  "Localize", "Internationalize", "Translate", "Summarize", "Paraphrase",
  "Tokenize", "Embed", "Vectorize", "Quantize", "Compress", "Decompress",
  "Minify", "Bundle", "Transpile", "Compile", "Interpret", "Execute", "Run",
  "Simulate", "Emulate", "Mock", "Stub", "Fake", "Inject", "Intercept",
  "Wrap", "Decorate", "Enhance", "Extend", "Override", "Inherit", "Compose",
  "Aggregate", "Reduce", "Map", "Flatten", "Group", "Join", "Split", "Merge",
  "Compare", "Diff", "Patch", "Sync", "Reconcile", "Resolve", "Handle",
  "Process", "Consume", "Produce", "Publish", "Subscribe", "Broadcast",
  "Multicast", "Unicast", "Relay", "Proxy", "Forward", "Redirect", "Rewrite",
  "Transform", "Adapt", "Convert", "Export", "Import", "Ingest", "Eject",
  "Render", "Pre-render", "Hydrate", "Dehydrate", "Suspend", "Resume", "Cancel",
  "Abort", "Retry", "Fallback", "Degrade", "Failover", "Recover", "Heal",
  "Self-heal", "Auto-scale", "Auto-tune", "Auto-repair", "Auto-discover",
];

const subjects: Record<string, string[]> = {
  "Code Generation": [
    "function", "class", "module", "library", "package", "component", "service",
    "microservice", "API", "endpoint", "controller", "resolver", "handler",
    "middleware", "plugin", "extension", "adapter", "bridge", "wrapper",
    "facade", "proxy", "decorator", "observer", "strategy", "factory",
    "builder", "singleton", "prototype", "pool", "queue", "stack", "heap",
    "tree", "graph", "matrix", "vector", "tensor", "array", "list", "map",
    "set", "dictionary", "hash table", "linked list", "binary tree", "trie",
    "B-tree", "red-black tree", "AVL tree", "segment tree", "Fenwick tree",
    "disjoint set", "union-find", "priority queue", "deque", "circular buffer",
    "ring buffer", "sliding window", "two-pointer technique", "recursion",
    "dynamic programming solution", "greedy algorithm", "backtracking solver",
    "branch and bound", "divide and conquer", "memoization wrapper",
    "cache layer", "session manager", "token generator", "password hasher",
    "encryption utility", "decryption utility", "compression tool",
    "decompression tool", "serialization module", "deserialization module",
    "validation schema", "sanitization filter", "parser", "lexer", "tokenizer",
    "interpreter", "compiler", "transpiler", "bundler", "minifier", "linter",
    "formatter", "test runner", "benchmark suite", "profiler", "debugger",
    "logger", "metrics collector", "tracer", "error handler", "exception catcher",
    "retry logic", "circuit breaker", "rate limiter", "throttler", "debouncer",
    "batcher", "stream processor", "event emitter", "pub-sub channel",
    "message broker", "job scheduler", "task queue", "worker pool",
    "thread pool", "process pool", "connection pool", "resource pool",
    "object pool", "memory allocator", "garbage collector", "reference counter",
    "weak reference", "soft reference", "phantom reference", "finalizer",
    "cleaner", "disposer", "destroyer", "initializer", "constructor",
    "destructor", "clone method", "copy method", "move method", "swap method",
    "compare method", "equals method", "hash method", "toString method",
    "fromString method", "serialize method", "deserialize method", "validate method",
    "sanitize method", "normalize method", "canonicalize method", "escape method",
    "unescape method", "encode method", "decode method", "encrypt method",
    "decrypt method", "sign method", "verify method", "compress method",
    "decompress method", "transform method", "map method", "filter method",
    "reduce method", "fold method", "scan method", "zip method", "unzip method",
    "flatten method", "chunk method", "partition method", "groupBy method",
    "sort method", "shuffle method", "sample method", "pick method", "omit method",
    "merge method", "diff method", "patch method", "intersect method",
    "union method", "difference method", "symmetric difference method",
    "cartesian product method", "power set method", "permutation method",
    "combination method", "subset method", "superset method", "disjoint method",
  ],
  "UI/UX Design": [
    "button", "input field", "dropdown menu", "modal dialog", "tooltip",
    "popover", "card", "badge", "avatar", "icon", "spinner", "progress bar",
    "slider", "toggle switch", "checkbox", "radio button", "tab panel",
    "accordion", "carousel", "gallery", "grid", "list", "table",
    "data table", "tree view", "menu bar", "navigation rail", "sidebar",
    "app bar", "toolbar", "fab", "bottom sheet",
    "snackbar", "banner", "chip", "tag", "pill", "divider", "spacer",
    "skeleton loader", "shimmer effect", "pulse animation", "fade animation",
    "slide animation", "scale animation", "rotate animation", "flip animation",
    "bounce animation", "elastic animation", "spring animation", "morph animation",
    "drawer", "panel", "pane", "splitter", "resizer", "dragger", "drop zone",
    "upload area", "preview zone", "cropper", "rotator", "zoomer", "panner",
    "scroller", "parallax layer", "sticky header", "fixed footer", "pinned column",
    "frozen row", "virtual list", "infinite scroll", "pagination control",
    "stepper", "wizard", "form", "survey", "quiz", "calculator", "converter",
    "picker", "selector", "chooser", "explorer", "navigator", "finder",
    "search bar", "filter panel", "sort control", "group control", "view switcher",
    "density selector", "theme toggler", "mode switcher", "layout chooser",
    "breakpoint indicator", "grid overlay", "ruler", "guide", "snap line",
    "measurement tool", "color eyedropper", "font inspector", "spacing checker",
    "contrast analyzer", "readability scorer", "accessibility validator",
    "focus indicator", "hover state", "active state", "disabled state",
    "loading state", "error state", "empty state", "success state", "warning state",
    "info state", "neutral state", "highlighted state", "selected state",
    "indeterminate state", "pressed state", "dragged state", "dropped state",
    "resized state", "maximized state", "minimized state", "collapsed state",
    "expanded state", "hidden state", "visible state", "locked state",
    "unlocked state", "read-only state", "editable state", "required field",
    "optional field", "validated field", "invalid field", "pending field",
  ],
  "API & Backend": [
    "REST endpoint", "GraphQL mutation", "GraphQL query", "gRPC service",
    "WebSocket channel", "SSE stream", "webhook receiver", "event listener",
    "message consumer", "message producer", "topic publisher", "queue worker",
    "cron job", "scheduled task", "background job", "async processor",
    "saga orchestrator", "compensating transaction", "two-phase commit",
    "distributed lock", "leader election", "consensus algorithm", "raft node",
    "paxos acceptor", "gossip protocol", "membership manager", "heartbeat monitor",
    "health probe", "readiness check", "liveness check", "startup probe",
    "metric exporter", "log shipper", "trace collector", "span processor",
    "baggage propagator", "context manager", "request interceptor",
    "response interceptor", "error interceptor", "retry interceptor",
    "timeout interceptor", "cache interceptor", "auth interceptor",
    "logging interceptor", "metrics interceptor", "tracing interceptor",
    "compression interceptor", "encryption interceptor", "validation interceptor",
    "sanitization interceptor", "rate limiting interceptor", "circuit breaker interceptor",
    "bulkhead interceptor", "hedging interceptor", "shadowing interceptor",
    "canary interceptor", "feature flag interceptor", "A/B test interceptor",
    "personalization interceptor", "recommendation interceptor", "search interceptor",
    "filter interceptor", "sort interceptor", "paginate interceptor", "cache warmer",
    "cache invalidator", "cache replicator", "cache sharding router",
    "database proxy", "read replica selector", "write coalescer", "batch inserter",
    "connection manager", "transaction coordinator", "savepoint manager",
    "deadlock detector", "lock timeout handler", "query planner", "index advisor",
    "schema migrator", "seed runner", "fixture loader", "mock server",
    "stub endpoint", "fake service", "simulator", "emulator", "proxy server",
    "reverse proxy", "forward proxy", "transparent proxy", "SOCKS proxy",
    "HTTP proxy", "TCP proxy", "UDP proxy", "load balancer", "traffic splitter",
    "request router", "path matcher", "host matcher", "header matcher",
    "cookie matcher", "query matcher", "body matcher", "method matcher",
    "protocol matcher", "port matcher", "IP matcher", "CIDR matcher",
    "geolocation matcher", "time matcher", "rate matcher", "quota matcher",
    "budget matcher", "priority matcher", "weight matcher", "latency matcher",
  ],
  "Data Analysis": [
    "dataset", "dataframe", "series", "column", "row", "cell", "index",
    "multi-index", "hierarchical index", "time index", "date range",
    "frequency", "period", "interval", "window", "rolling window",
    "expanding window", "ewm", "resampler",
    "grouper", "aggregator", "transformer", "applier", "filter",
    "selector", "assigner", "merger", "joiner", "concatenator",
    "stacker", "unstacker", "pivoter", "melter", "crosstab",
    "pivot table", "contingency table", "frequency table", "summary table",
    "descriptive statistics", "inferential statistics", "hypothesis test",
    "confidence interval", "p-value calculator", "effect size estimator",
    "power analyzer", "sample size calculator", "bootstrapping engine",
    "permutation test", "Monte Carlo simulation", "Markov chain",
    "Bayesian network", "causal graph", "DAG", "directed graph",
    "undirected graph", "bipartite graph", "multigraph", "hypergraph",
    "tree structure", "forest", "path", "cycle", "clique", "community",
    "centrality measure", "betweenness", "closeness", "eigenvector",
    "PageRank", "HITS", "clustering coefficient", "density", "diameter",
    "radius", "eccentricity", "periphery", "core", "shell", "layer",
    "embedding", "latent space", "manifold", "t-SNE", "UMAP", "PCA",
    "LDA", "NMF", "ICA", "FA", "CCA", "PLS", "RDA",
    "kernel method", "RBF kernel", "polynomial kernel", "linear kernel",
    "sigmoid kernel", "cosine kernel", "laplacian kernel", "graph kernel",
    "string kernel", "tree kernel", "spectrum kernel", "histogram kernel",
    "feature extractor", "feature selector", "feature transformer",
    "feature scaler", "normalizer", "standardizer", "robust scaler",
    "quantile transformer", "power transformer", "log transformer",
    "box-cox transformer", "yeo-johnson transformer", "binarizer",
    "one-hot encoder", "label encoder", "ordinal encoder", "target encoder",
    "frequency encoder", "hashing encoder", "binary encoder", "base-N encoder",
    "backward difference encoder", "helmert encoder", "polynomial encoder",
    "sum encoder", "mean encoder", "WOE encoder", "LOO encoder",
    "smoothing estimator", "shrinkage estimator", "ridge estimator",
    "lasso estimator", "elastic net", "SGD classifier", "SGD regressor",
    "passive aggressive classifier", "perceptron", "MLP classifier",
    "MLP regressor", "RBF network", "SVM classifier", "SVM regressor",
    "nu-SVM", "one-class SVM", "linear SVM", "kernel SVM", "tree classifier",
    "tree regressor", "extra trees classifier", "extra trees regressor",
    "random forest classifier", "random forest regressor", "gradient boosting",
    "AdaBoost", "XGBoost", "LightGBM", "CatBoost", "HistGradientBoosting",
    "voting classifier", "voting regressor", "stacking classifier",
    "stacking regressor", "bagging classifier", "bagging regressor",
    "KNN classifier", "KNN regressor", "radius neighbors", "nearest centroid",
    "naive Bayes", "Gaussian NB", "multinomial NB", "complement NB",
    "Bernoulli NB", "categorical NB", "LDA classifier", "QDA classifier",
    "Gaussian process classifier", "Gaussian process regressor",
    "isotonic regression", "PLS regression", "CCA regression", "RANSAC",
    "Theil-Sen estimator", "Huber regressor", "quantile regressor",
    "Tweedie regressor", "Poisson regressor", "Gamma regressor",
    "inverse Gaussian regressor", "negative binomial regressor",
    "ordinal regressor", "multinomial regressor", "cox proportional hazards",
    "survival SVM", "survival tree", "survival forest", "gradient boosting survival",
    "Kaplan-Meier estimator", "Nelson-Aalen estimator", "Breslow estimator",
    "Aalen-Johansen estimator", "Fine-Gray model", "competing risks model",
    "multi-state model", "frailty model", "shared frailty", "nested frailty",
    "recurrent events model", "panel data model", "mixed effects model",
    "random effects model", "fixed effects model", "difference-in-differences",
    "synthetic control", "regression discontinuity", "instrumental variables",
    "2SLS", "3SLS", "GMM", "system GMM", "Arellano-Bond", "Blundell-Bond",
    "spatial lag model", "spatial error model", "SAR", "SEM", "SDM", "SDEM",
    "SAC", "GNS", "spatial Durbin", "spatial Durbin error", "spatial moving average",
    "CAR", "SARMA", "SARAR", "Cliff-Ord", "geographically weighted regression",
    "multiscale GWR", "spatially varying coefficients", "eigenvector spatial filter",
    "Moran eigenvector", "spatial constrained clustering", "SKATER",
    "REDCAP", "AZP", "max-p regions", "ARiSeL", "AMOEBA", "SCCA",
  ],
  "Content Creation": [
    "headline", "title", "subtitle", "tagline", "slogan", "hook",
    "lead paragraph", "body copy", "closing argument", "call to action",
    "value proposition", "unique selling point", "differentiator",
    "proof point", "testimonial", "case study", "success story",
    "customer quote", "expert endorsement", "influencer mention",
    "social proof", "trust signal", "credibility marker", "authority badge",
    "guarantee statement", "risk reversal", "objection handler",
    "FAQ item", "comparison point", "feature highlight", "benefit statement",
    "outcome promise", "transformation story", "before and after",
    "milestone celebration", "achievement announcement", "launch announcement",
    "product reveal", "teaser campaign", "countdown sequence", "launch event",
    "webinar script", "workshop outline", "course curriculum", "lesson plan",
    "module summary", "chapter overview", "section header", "topic sentence",
    "supporting detail", "evidence citation", "data visualization caption",
    "image alt text", "video transcript", "audio transcript", "podcast show notes",
    "episode summary", "guest bio", "host introduction", "sponsor read",
    "ad script", "jingle lyrics", "theme song", "sound effect description",
    "music cue sheet", "storyboard description", "shot list item",
    "camera direction", "lighting note", "wardrobe description",
    "prop list item", "location description", "set design note",
    "special effects description", "CGI brief", "animation keyframe description",
    "voiceover script", "narration track", "subtitle text", "caption text",
    "chiron text", "lower third text", "end card text", "bumpers text",
    "transition text", "split screen description", "picture-in-picture description",
    "green screen description", "overlay text", "annotation text",
    "highlight description", "zoom description", "pan description",
    "tilt description", "tracking shot description", "dolly shot description",
    "crane shot description", "drone shot description", "steady shot description",
    "handheld shot description", "POV shot description", "reaction shot description",
    "establishing shot description", "cutaway description", "insert shot description",
    "montage description", "sequence description", "scene description",
    "act break description", "climax description", "resolution description",
    "denouement description", "epilogue description", "prologue description",
    "foreshadowing description", "flashback description", "flash-forward description",
    "dream sequence description", "nightmare sequence description",
    "vision description", "hallucination description", "memory description",
    "imagined scenario description", "parallel universe description",
    "alternate timeline description", "what-if scenario description",
  ],
  "Business Strategy": [
    "market segment", "customer persona", "buyer profile", "ideal customer",
    "champion user", "power user", "early adopter", "late majority",
    "laggard", "innovator", "visionary", "pragmatist", "conservative",
    "skeptic", "blocker", "detractor", "passive", "neutral", "promoter",
    "advocate", "evangelist", "ambassador", "referral source", "affiliate partner",
    "channel partner", "reseller", "distributor", "wholesaler", "retailer",
    "direct sales", "inside sales", "field sales", "enterprise sales",
    "SMB sales", "self-service", "product-led growth", "sales-led growth",
    "marketing-led growth", "community-led growth", "partner-led growth",
    "channel-led growth", "event-led growth", "content-led growth",
    "SEO-led growth", "SEM-led growth", "social-led growth", "viral loop",
    "network effect", "flywheel", "growth loop", "retention loop",
    "engagement loop", "monetization loop", "acquisition loop",
    "activation loop", "referral loop", "revenue loop", "profit loop",
    "cost structure", "revenue stream", "pricing tier", "plan level",
    "package deal", "bundle offer", "addon feature", "upsell path",
    "cross-sell opportunity", "downsell option", "freemium model",
    "trial period", "money-back guarantee", "annual commitment",
    "monthly subscription", "usage-based billing", "seat-based pricing",
    "transaction-based pricing", "revenue share model", "royalty model",
    "licensing model", "franchise model", "white-label model",
    "API-based revenue", "data monetization", "advertising revenue",
    "sponsorship revenue", "consulting revenue", "training revenue",
    "certification revenue", "support revenue", "premium support",
    "managed service", "professional service", "implementation service",
    "integration service", "migration service", "optimization service",
    "audit service", "assessment service", "health check service",
    "workshop service", "coaching service", "advisory service",
    "retainer agreement", "SOW", "MSA", "NDA", "SLA", "SLO",
    "SLI", "KPI", "OKR", "KRI", "KCI", "metrics definition",
    "dashboard design", "report template", "scorecard layout",
    "benchmark comparison", "trend analysis", "variance analysis",
    "root cause analysis", "fishbone diagram", "5 whys analysis",
    "PEST analysis", "Porter's five forces", "value chain analysis",
    "blue ocean strategy", "red ocean strategy", "differentiation strategy",
    "cost leadership", "focus strategy", "integrated strategy",
    "niche strategy", "mass market strategy", "platform strategy",
    "ecosystem strategy", "API strategy", "data strategy",
    "AI strategy", "cloud strategy", "security strategy",
    "compliance strategy", "sustainability strategy", "ESG strategy",
    "DEI strategy", "talent strategy", "culture strategy",
    "remote work strategy", "hybrid work strategy", "office strategy",
    "real estate strategy", "geographic expansion", "market entry",
    "market penetration", "market development", "product development",
    "diversification", "acquisition target", "merger plan",
    "spin-off strategy", "joint venture", "strategic alliance",
    "coopetition", "partnership program", "channel program",
    "reseller program", "affiliate program", "referral program",
    "loyalty program", "rewards program", "incentive program",
    "commission structure", "bonus plan", "equity plan",
    "ESOP", "profit sharing", "revenue sharing", "gain sharing",
    "stock options", "RSU", "PSU", "phantom stock", "SAR",
    "deferred compensation", "retention bonus", "signing bonus",
    "performance bonus", "spot bonus", "team bonus",
    "company bonus", "holiday bonus", "referral bonus",
    "sales quota", "sales target", "sales forecast",
    "pipeline analysis", "funnel analysis", "win rate analysis",
    "deal velocity", "sales cycle length", "ACV", "ARPU",
    "LTV", "CAC", "LTV/CAC ratio", "payback period",
    "gross margin", "net margin", "operating margin",
    "EBITDA margin", "free cash flow", "burn rate",
    "runway", "break-even point", "profitability timeline",
    "valuation multiple", "revenue multiple", "EBITDA multiple",
    "DCF valuation", "comparable analysis", "precedent analysis",
    "LBO model", "M&A model", "integration plan", "synergy target",
    "cost savings", "revenue uplift", "cross-sell synergy",
    "technology synergy", "talent synergy", "market synergy",
    "brand synergy", "customer synergy", "data synergy",
    "IP synergy", "patent synergy", "R&D synergy",
    "manufacturing synergy", "supply chain synergy",
    "procurement synergy", "IT synergy", "facilities synergy",
    "corporate strategy", "business unit strategy", "functional strategy",
    "operational strategy", "competitive strategy", "cooperative strategy",
  ],
  "Database & SQL": [
    "table", "view", "materialized view", "index", "unique index",
    "composite index", "partial index", "expression index",
    "GIN index", "GIST index", "SP-GIST index", "BRIN index",
    "hash index", "B-tree index", "clustered index", "non-clustered index",
    "covering index", "include index", "filter index", "partition",
    "subpartition", "range partition", "list partition", "hash partition",
    "composite partition", "interval partition", "reference partition",
    "system partition", "external table", "foreign table", "temporary table",
    "global temporary table", "local temporary table", "unlogged table",
    "memory table", "columnar table", "row store", "column store",
    "hybrid store", "wide table", "narrow table", "fact table",
    "dimension table", "bridge table", "junction table", "link table",
    "mapping table", "lookup table", "reference table", "configuration table",
    "audit table", "log table", "history table", "archive table",
    "staging table", "ETL table", "transform table", "load table",
    "extract table", "source table", "target table", "sink table",
    "buffer table", "queue table", "stack table", "heap table",
    "pool table", "cache table", "session table", "transaction table",
    "lock table", "semaphore table", "barrier table", "latch table",
    "mutex table", "spinlock table", "rwlock table", "sequence",
    "identity column", "auto-increment", "serial column", "UUID column",
    "ULID column", "snowflake ID", "timestamp column", "date column",
    "time column", "datetime column", "timestamptz column", "interval column",
    "range column", "array column", "JSON column", "JSONB column",
    "XML column", "hstore column", "ltree column", "lquery column",
    "cube column", "point column", "line column", "circle column",
    "box column", "path column", "polygon column", "geometry column",
    "geography column", "raster column", "network column", "MAC address column",
    "IP address column", "CIDR column", "INET column", "bit string column",
    "varbit column", "bytea column", "BLOB column", "CLOB column",
    "NCLOB column", "text column", "varchar column", "char column",
    "nvarchar column", "nchar column", "boolean column", "integer column",
    "bigint column", "smallint column", "tinyint column", "decimal column",
    "numeric column", "real column", "float column", "double column",
    "money column", "currency column", "enum column", "set column",
    "composite type", "domain type", "distinct type", "row type",
    "record type", "cursor", "refcursor", "portal", "prepared statement",
    "bound statement", "stored procedure", "function", "trigger function",
    "event trigger", "DDL trigger", "DML trigger", "instead of trigger",
    "compound trigger", "system trigger", "user trigger", "constraint trigger",
    "deferred trigger", "immediate trigger", "before trigger", "after trigger",
    "for each row trigger", "for each statement trigger", "cascading trigger",
    "recursive trigger", "nested trigger", "serializable transaction",
    "repeatable read transaction", "read committed transaction",
    "read uncommitted transaction", "snapshot isolation", "optimistic locking",
    "pessimistic locking", "MVCC", "multi-version concurrency",
    "two-phase locking", "timestamp ordering", "validation concurrency",
    "write-skew detection", "phantom read detection", "non-repeatable read detection",
    "dirty read detection", "lost update detection", "deadlock detection",
    "deadlock prevention", "wait-die scheme", "wound-wait scheme",
    "timeout scheme", "immediate restart", "queued lock", "priority lock",
    "fair lock", "unfair lock", "reentrant lock", "non-reentrant lock",
    "shared lock", "exclusive lock", "update lock", "intent lock",
    "schema lock", "metadata lock", "DDL lock", "backup lock",
    "flush lock", "tablespace lock", "page lock", "row lock",
    "key lock", "gap lock", "next-key lock", "insert intention lock",
    "auto-increment lock", "predicate lock", "transaction lock",
    "savepoint", "rollback", "commit", "prepare", "commit prepared",
    "rollback prepared", "two-phase commit", "three-phase commit",
    "XA transaction", "distributed transaction", "nested transaction",
    "chained transaction", "autonomous transaction", "subtransaction",
    "compensating transaction", "saga", "event sourcing", "CQRS",
    "read model", "write model", "projection", "rehydration",
    "snapshot", "event store", "command handler", "event handler",
    "query handler", "saga orchestrator", "saga participant",
  ],
  "DevOps & Cloud": [
    "container image", "base image", "layer", "Dockerfile instruction",
    "multi-stage build", "build cache", "image registry", "image tag",
    "image digest", "manifest", "OCI spec", "container runtime",
    "containerd", "CRI-O", "runc", "gVisor", "Kata containers",
    "Firecracker microVM", "Pod", "Deployment", "StatefulSet",
    "DaemonSet", "ReplicaSet", "Job", "CronJob", "Service",
    "Ingress", "Ingress controller", "LoadBalancer", "NodePort",
    "ClusterIP", "Headless service", "ExternalName", "EndpointSlice",
    "NetworkPolicy", "CNI plugin", "Calico", "Flannel", "Weave",
    "Cilium", "Antrea", "OVN-Kubernetes", "ConfigMap", "Secret",
    "ExternalSecret", "SealedSecret", "VaultSecret", "PersistentVolume",
    "PersistentVolumeClaim", "StorageClass", "VolumeSnapshot",
    "CSI driver", "ResourceQuota", "LimitRange", "PriorityClass",
    "PodDisruptionBudget", "HorizontalPodAutoscaler", "VerticalPodAutoscaler",
    "ClusterAutoscaler", "Karpenter", "Fargate", "EC2", "Spot instance",
    "Reserved instance", "On-demand instance", "Dedicated host",
    "Placement group", "Auto Scaling group", "Launch template",
    "Launch configuration", "AMI", "Snapshot", "EBS volume",
    "EFS filesystem", "FSx", "S3 bucket", "S3 object", "S3 prefix",
    "Glacier archive", "CloudFront distribution", "Route53 record",
    "ALB", "NLB", "CLB", "Target group", "Listener", "Rule",
    "WAF", "Shield", "GuardDuty", "Inspector", "Macie",
    "Detective", "Security Hub", "IAM role", "IAM policy",
    "IAM user", "IAM group", "Service account", "Federated identity",
    "SAML provider", "OIDC provider", "Cognito pool", "API Gateway",
    "AppSync", "EventBridge", "SQS queue", "SNS topic", "Kinesis stream",
    "MSK cluster", "Step Functions", "SWF", "Batch job", "Glue job",
    "EMR cluster", "Redshift cluster", "Athena query", "Lake Formation",
    "QuickSight", "Data Pipeline", "DMS task", "Snowball device",
    "Transfer Family", "Storage Gateway", "Direct Connect",
    "Site-to-Site VPN", "Client VPN", "Transit Gateway", "VPC",
    "Subnet", "Route table", "Internet gateway", "NAT gateway",
    "VPC endpoint", "VPC peering", "VPC lattice", "CloudWatch alarm",
    "CloudWatch log", "CloudWatch metric", "CloudWatch event",
    "X-Ray trace", "CodePipeline", "CodeBuild", "CodeDeploy",
    "CodeCommit", "CodeStar", "Cloud9", "CloudShell", "SSM parameter",
    "SSM document", "SSM automation", "OpsCenter", "Systems Manager",
    "AppConfig", "CloudFormation stack", "Terraform state",
    "Terraform module", "Terraform workspace", "Pulumi stack",
    "Ansible playbook", "Ansible role", "Ansible inventory",
    "Chef cookbook", "Chef recipe", "Puppet manifest", "Puppet module",
    "Salt state", "Salt pillar", "Salt grain", "Vagrant box",
    "Vagrantfile", "Packer template", "Packer builder", "Packer provisioner",
    "Packer post-processor", "Nomad job", "Nomad task", "Nomad group",
    "Nomad allocation", "Consul service", "Consul KV", "Consul ACL",
    "Vault policy", "Vault path", "Vault engine", "Vault lease",
    "Vault token", "Vault approle", "Vault Kubernetes auth",
    "Vault AWS auth", "Vault Azure auth", "Vault GCP auth",
    "Vault OIDC auth", "Vault LDAP auth", "Vault Okta auth",
    "Vault GitHub auth", "Vault token auth", "Boundary target",
    "Boundary session", "Waypoint project", "Waypoint application",
    "Waypoint deployment", "Waypoint release", "Waypoint build",
  ],
  "Mobile Development": [
    "screen", "fragment", "activity", "view controller", "scene",
    "segue", "navigation controller", "tab bar controller",
    "page view controller", "split view controller", "collection view",
    "table view", "scroll view", "stack view", "web view", "map view",
    "camera view", "video view", "image view", "text view",
    "text field", "text area", "label", "button", "switch",
    "slider", "stepper", "segmented control", "date picker",
    "time picker", "color picker", "image picker", "document picker",
    "contact picker", "location picker", "media player", "audio player",
    "video player", "AV player", "ExoPlayer", "MediaPlayer",
    "Notification", "Local notification", "Push notification",
    "Silent notification", "Background notification", "Data notification",
    "Alert notification", "Banner notification", "Badge update",
    "Sound notification", "Vibration pattern", "Haptic feedback",
    "Tap gesture", "Long press gesture", "Pan gesture", "Swipe gesture",
    "Pinch gesture", "Rotation gesture", "Screen edge gesture",
    "Force touch gesture", "Hover gesture", "Mouse gesture",
    "Keyboard shortcut", "Hardware button handler", "Volume button handler",
    "Power button handler", "Home button handler", "Back button handler",
    "Menu button handler", "Search button handler", "Camera button handler",
    "Headphone jack handler", "Bluetooth handler", "NFC handler",
    "QR code scanner", "Barcode scanner", "OCR scanner", "Face detector",
    "Object detector", "Pose detector", "Text detector", "Landmark detector",
    "Speech recognizer", "Text-to-speech engine", "Language identifier",
    "Translator", "Sentiment analyzer", "Entity extractor", "Smart reply generator",
    "App clip", "Instant app", "Widget", "Live activity", "Dynamic island",
    "App extension", "Share extension", "Action extension", "Today extension",
    "Photo editing extension", "Document provider", "Custom keyboard",
    "Sticker pack", "iMessage app", "Watch app", "Watch complication",
    "TV app", "CarPlay app", "Mac Catalyst app", "UIKit app",
    "SwiftUI app", "Jetpack Compose app", "Flutter app", "React Native app",
    "Ionic app", "Cordova app", "Capacitor app", "NativeScript app",
    "Xamarin app", "Unity app", "Unreal app", "Godot app", "Cocos app",
    "SpriteKit app", "SceneKit app", "ARKit app", "CoreML app",
    "Vision app", "NaturalLanguage app", "Speech app", "SiriKit app",
    "Intents app", "Shortcuts app", "HealthKit app", "CareKit app",
    "ResearchKit app", "CoreMotion app", "CoreLocation app",
    "MapKit app", "CoreBluetooth app", "NearbyInteraction app",
    "MultipeerConnectivity app", "GameKit app", "GameCenter app",
    "ReplayKit app", "Photos app", "CoreImage app", "Metal app",
    "CoreAnimation app", "CoreGraphics app", "CoreText app",
    "PDFKit app", "QuickLook app", "CoreSpotlight app",
    "StoreKit app", "CoreData app", "CloudKit app", "Firebase app",
    "Supabase app", "Realm app", "Room app", "SQLite app",
    "MMKV app", "UserDefaults app", "SharedPreferences app",
    "Keychain app", "KeyStore app", "SecureEnclave app",
    "BiometricPrompt app", "LocalAuthentication app",
  ],
  "AI Model Tuning": [
    "attention head", "attention layer", "self-attention", "cross-attention",
    "multi-head attention", "scaled dot-product attention", "causal attention",
    "bidirectional attention", "sparse attention", "linear attention",
    "flash attention", "memory-efficient attention", "sliding window attention",
    "global attention", "local attention", "strided attention", "dilated attention",
    "ring attention", "zigzag attention", "blockwise attention",
    "encoder layer", "decoder layer", "transformer block", "residual connection",
    "layer normalization", "batch normalization", "group normalization",
    "instance normalization", "weight normalization", "spectral normalization",
    "cosine normalization", "response normalization", "local response normalization",
    "switchable normalization", "filter response normalization", "transformer layer",
    "embedding layer", "positional encoding", "learned positional embedding",
    "rotary positional embedding", "ALiBi", "xPos", "relative positional bias",
    "token embedding", "word embedding", "character embedding", "subword embedding",
    "sentence embedding", "paragraph embedding", "document embedding",
    "contextual embedding", "static embedding", "dynamic embedding",
    "pre-trained embedding", "fine-tuned embedding", "adapter layer",
    "LoRA layer", "QLoRA layer", "DoRA layer", "prefix tuning layer",
    "prompt tuning layer", "P-tuning layer", "IA3 layer", "BitFit layer",
    "diff pruning", "mask tuning", "layer dropping", "progressive layer dropping",
    "knowledge distillation", "teacher model", "student model",
    "intermediate layer matching", "attention transfer", "logit matching",
    "feature matching", "relation matching", "response matching",
    "hint learning", "born-again network", "mutual learning",
    "self-distillation", "online distillation", "offline distillation",
    "data-free distillation", "zero-shot distillation", "task-agnostic distillation",
    "cross-lingual distillation", "multi-teacher distillation",
    "ensemble distillation", "stochastic depth", "dropout layer",
    "dropconnect layer", "dropblock layer", "drop path", "mixup layer",
    "cutmix layer", "cutout layer", "random erasing", "auto augmentation",
    "rand augmentation", "trivial augmentation", "feature-wise linear modulation",
    "FiLM layer", "conditional batch norm", "adaptive instance norm",
    "SPADE layer", "SE layer", "SK layer", "ECA layer", "CBAM layer",
    "BAM layer", "GC layer", "NL layer", "CC layer", "AA layer",
    "DAN layer", "PAM layer", "CAM layer", "SAM layer", "EMA layer",
    "CoaT layer", "MViT layer", "Swin layer", "SwinV2 layer",
    "PVT layer", "PVTv2 layer", "Twins layer", "CSWin layer",
    "MaxViT layer", "FastViT layer", "EfficientViT layer",
    "MobileViT layer", "EdgeViT layer", "CrossViT layer",
    "BEiT layer", "iBOT layer", "DINO layer", "DINOv2 layer",
    "MAE layer", "SimMIM layer", "Mask2Former layer",
    "data2vec layer", "ImageBind layer", "AudioMAE layer",
    "VideoMAE layer", "Point-MAE layer", "ACT layer",
    "prompt encoder", "mask decoder", "image encoder",
    "text encoder", "vision encoder", "audio encoder",
    "video encoder", "multimodal encoder", "fusion encoder",
    "contrastive head", "projection head", "prediction head",
    "classification head", "regression head", "detection head",
    "segmentation head", "captioning head", "generation head",
    "translation head", "summarization head", "question answering head",
    "reasoning head", "planning head", "control head", "policy head",
    "value head", "advantage head", "critic head", "actor head",
    "world model", "dynamics model", "reward model", "termination model",
    "encoder-decoder", "encoder-only", "decoder-only", "autoencoder",
    "variational autoencoder", "VQ-VAE", "VQ-GAN", "diffusion model",
    "DDPM", "DDIM", "PLMS", "DPM-Solver", "DPM-Solver++",
    "UniPC", "Euler", "Heun", "LMS", "ancestral sampler",
    "stochastic sampler", "deterministic sampler", "k-diffusion",
    "compvis diffusion", "stable diffusion", "latent diffusion",
    "guided diffusion", "classifier guidance", "classifier-free guidance",
    "CFG", "negative prompt", "prompt weighting", "token merging",
    "token pruning", "token shifting", "token mixing", "token routing",
    "MoE layer", "expert layer", "gate layer", "router layer",
    "top-k routing", "top-p routing", "expert choice routing",
    "load balancing loss", "router z-loss", "expert dropout",
    "expert parallelism", "tensor parallelism", "pipeline parallelism",
    "sequence parallelism", "context parallelism", "data parallelism",
    "fully sharded data parallelism", "ZeRO stage 1", "ZeRO stage 2",
    "ZeRO stage 3", "ZeRO-Offload", "ZeRO-Infinity", "DeepSpeed",
    "FSDP", "Megatron-LM", "Megatron-Core", "NeMo", "Colossal-AI",
    "Alpa", "Pax", "Orbax", "T5X", "Jax", "Flax", "Optax",
    "Haiku", "Equinox", "Keras", "TF-Agents", "TF-Text",
  ],
  "Cybersecurity": [
    "firewall rule", "IDS signature", "IPS rule", "WAF rule",
    "DLP policy", "SIEM correlation rule", "SOAR playbook",
    "threat intelligence feed", "IOCs", "IOAs", "TTPs",
    "MITRE ATT&CK technique", "MITRE D3FEND countermeasure",
    "CVE", "CWE", "CVSS score", "EPSS score", "KEV catalog",
    "CISA advisory", "NCSC guidance", "NIST control", "ISO 27001 control",
    "SOC 2 control", "PCI DSS control", "HIPAA control", "GDPR control",
    "CCPA control", "SOX control", "FISMA control", "FedRAMP control",
    "CMMC control", "NIST 800-53 control", "NIST 800-171 control",
    "CIS benchmark", "STIG", "SCAP", "XCCDF", "OVAL", "OCIL",
    "SARIF", "CSA CCM", "CSA STAR", "ISO 27701", "ISO 27017",
    "ISO 27018", "ISO 22301", "ISO 31000", "COBIT", "ITIL",
    "TOGAF", "SABSA", "O-ISM3", "HITRUST", "NIST CSF",
    "NIST RMF", "NIST Privacy Framework", "FAIR", "Risk IT",
    "Val IT", "M_o_R", "APR", "CRISC", "CISM", "CISSP",
    "GSEC", "GCIH", "GCIA", "GCFA", "GCFE", "GREM",
    "GWEB", "GPEN", "GWAPT", "GXPN", "OSCP", "OSCE",
    "OSEP", "OSWE", "OSED", "OSEE", "eJPT", "eCPPT",
    "eCMAP", "eWPT", "eWPTX", "eMAPT", "eCXD", "PNPT",
    "PTP", "AWAE", "AWPT", "ASAE", "ACSE", "SANS",
    "FOR500", "FOR508", "FOR572", "FOR578", "FOR610",
    "SEC504", "SEC560", "SEC575", "SEC660", "SEC760",
    "MGT512", "MGT514", "MGT516", "MGT433", "AUD507",
    "penetration test", "vulnerability assessment", "red team exercise",
    "blue team exercise", "purple team exercise", "bug bounty program",
    "security audit", "compliance audit", "architecture review",
    "code review", "configuration review", "policy review",
    "procedure review", "risk assessment", "threat modeling session",
    "attack tree analysis", "kill chain analysis", "diamond model analysis",
    "cyber exercise", "tabletop exercise", "simulation exercise",
    "drill exercise", "validation exercise", "assessment exercise",
  ],
  "Project Management": [
    "project charter", "scope statement", "WBS", "activity list",
    "milestone list", "schedule baseline", "cost baseline", "quality baseline",
    "risk register", "stakeholder register", "issue log", "change log",
    "decision log", "assumption log", "constraint log", "dependency log",
    "resource calendar", "team charter", "RACI matrix", "RAM",
    "OBS", "PBS", "RBS", "CBS", "FBS", "accountability chart",
    "communication plan", "meeting agenda", "meeting minutes", "status report",
    "progress report", "variance report", "forecast report", "earned value report",
    "risk report", "issue report", "quality report", "stakeholder report",
    "team report", "financial report", "resource report", "procurement report",
    "benefits report", "lessons learned report", "closure report",
    "project proposal", "business case", "feasibility study",
    "cost-benefit analysis", "ROI calculation", "NPV analysis",
    "IRR analysis", "payback analysis", "TCO analysis", "TCO model",
    "budget estimate", "rough order of magnitude", "definitive estimate",
    "bottom-up estimate", "top-down estimate", "parametric estimate",
    "analogous estimate", "three-point estimate", "PERT analysis",
    "Monte Carlo simulation", "critical path method", "CPM diagram",
    "PERT chart", "Gantt chart", "milestone chart", "bar chart",
    "S-curve", "burn-down chart", "burn-up chart", "velocity chart",
    "cumulative flow diagram", "cycle time scatter plot",
    "control chart", "histogram", "Pareto chart", "fishbone diagram",
    "flowchart", "process map", "value stream map", "swimlane diagram",
    "timeline", "roadmap", "backlog", "product backlog", "sprint backlog",
    "release backlog", "portfolio backlog", "program backlog",
    "epic", "feature", "story", "task", "subtask", "bug", "defect",
    "issue", "risk", "opportunity", "impediment", "blocker",
    "dependency", "constraint", "assumption", "requirement",
    "specification", "design", "prototype", "mockup", "wireframe",
    "user flow", "journey map", "service blueprint", "ecosystem map",
    "stakeholder map", "power-interest grid", "salience model",
    "influence diagram", "system diagram", "context diagram",
    "data flow diagram", "entity relationship diagram", "class diagram",
    "sequence diagram", "activity diagram", "state machine diagram",
    "component diagram", "deployment diagram", "network diagram",
    "architecture diagram", "infrastructure diagram", "security diagram",
    "integration diagram", "migration diagram", "transformation diagram",
  ],
};

const contexts = [
  "real-time data", "high traffic", "mobile users", "enterprise clients",
  "global deployment", "multi-tenant setup", "microservices", "serverless",
  "edge computing", "IoT devices", "batch processing", "stream processing",
  "event-driven", "data pipeline", "ML inference", "blockchain",
  "e-commerce", "healthcare", "finance", "education", "gaming",
  "social media", "content delivery", "analytics", "reporting",
  "monitoring", "alerting", "logging", "tracing", "auditing",
];

const technologies = [
  "React", "Vue", "Angular", "Svelte", "Next.js", "Nuxt", "Remix",
  "Node.js", "Deno", "Bun", "Python", "Rust", "Go", "Java",
  "Kotlin", "Swift", "C#", "TypeScript", "GraphQL", "tRPC",
  "WebSocket", "gRPC", "REST", "SOAP", "JSON-RPC", "Firebase",
  "Supabase", "AWS", "Azure", "GCP", "Docker", "Kubernetes",
  "Terraform", "Ansible", "Jenkins", "GitHub Actions", "GitLab CI",
  "CircleCI", "Travis CI", "ArgoCD", "Flux", "Istio", "Envoy",
  "Nginx", "HAProxy", "Redis", "PostgreSQL", "MySQL", "MongoDB",
  "Elasticsearch", "Kafka", "RabbitMQ", "SQS", "Pub/Sub",
  "OpenAI", "Claude", "Llama", "HuggingFace", "TensorFlow",
  "PyTorch", "scikit-learn", "Pandas", "NumPy", "Spark",
];

const features = [
  "authentication", "authorization", "caching", "rate limiting",
  "logging", "monitoring", "tracing", "metrics", "alerts",
  "notifications", "search", "filtering", "sorting", "pagination",
  "real-time updates", "offline support", "sync", "backup",
  "encryption", "compression", "validation", "sanitization",
  "i18n", "a11y", "responsive design", "dark mode", "animations",
  "drag and drop", "file upload", "image processing", "video streaming",
  "push notifications", "deep linking", "biometrics", "OAuth",
  "SSO", "2FA", "webhooks", "web workers", "service workers",
  "PWA features", "SSR", "SSG", "ISR", "CSR", "edge rendering",
];

function getPhrase(category: string, action: string, subject: string): string {
  const templates = [
    `${action} a ${subject} for ${contexts[Math.floor(Math.random() * contexts.length)]}`,
    `${action} a ${subject} using ${technologies[Math.floor(Math.random() * technologies.length)]}`,
    `${action} a ${subject} with ${features[Math.floor(Math.random() * features.length)]}`,
    `Build a ${subject} that supports ${features[Math.floor(Math.random() * features.length)]}`,
    `Create a ${subject} for ${contexts[Math.floor(Math.random() * contexts.length)]}`,
    `Design a ${subject} using ${technologies[Math.floor(Math.random() * technologies.length)]}`,
    `Implement a ${subject} with ${features[Math.floor(Math.random() * features.length)]}`,
    `Generate a ${subject} for ${contexts[Math.floor(Math.random() * contexts.length)]}`,
    `Optimize a ${subject} for ${features[Math.floor(Math.random() * features.length)]}`,
    `Debug a ${subject} that handles ${contexts[Math.floor(Math.random() * contexts.length)]}`,
    `Refactor a ${subject} to use ${technologies[Math.floor(Math.random() * technologies.length)]}`,
    `Deploy a ${subject} with ${features[Math.floor(Math.random() * features.length)]}`,
    `Scale a ${subject} to handle ${contexts[Math.floor(Math.random() * contexts.length)]}`,
    `Secure a ${subject} using ${technologies[Math.floor(Math.random() * technologies.length)]}`,
    `Automate a ${subject} for ${features[Math.floor(Math.random() * features.length)]}`,
    `Integrate a ${subject} with ${technologies[Math.floor(Math.random() * technologies.length)]}`,
  ];
  return templates[Math.floor(Math.random() * templates.length)];
}

export async function seed() {
  const db = getDb();
  console.log("Seeding phrases...");

  const existing = await db.select({ count: count() }).from(phrases);
  if (existing[0]?.count > 0) {
    console.log("Phrases already seeded:", existing[0].count);
    return;
  }

  const allPhrases: { english: string; category: string; difficulty: number }[] = [];

  for (const category of categories) {
    const categorySubjects = subjects[category] || ["system", "component", "module"];
    const used = new Set<string>();

    for (let i = 0; i < 250; i++) {
      const action = actions[i % actions.length];
      const subject = categorySubjects[i % categorySubjects.length];
      let phraseText = getPhrase(category, action, subject);

      // Ensure uniqueness within category
      let attempts = 0;
      while (used.has(phraseText) && attempts < 10) {
        phraseText = getPhrase(category, action, subject);
        attempts++;
      }
      used.add(phraseText);

      allPhrases.push({
        english: phraseText,
        category,
        difficulty: (i % 5) + 1,
      });
    }
  }

  // Insert in batches of 100
  const batchSize = 100;
  for (let i = 0; i < allPhrases.length; i += batchSize) {
    const batch = allPhrases.slice(i, i + batchSize);
    await db.insert(phrases).values(batch);
    console.log(`Inserted ${Math.min(i + batchSize, allPhrases.length)} / ${allPhrases.length} phrases`);
  }

  console.log("Done seeding", allPhrases.length, "phrases!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
